name: Lint Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run DotNet Analyzers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Code Analysis
        run: dotnet build --no-restore /warnaserror
