name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: SonarCloud Scan with Test Coverage
    runs-on: windows-latest

    steps:
      # 1. Check out the repository.
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. List repository structure to verify the correct folder path.
      - name: List Repository Structure
        shell: powershell
        run: |
          Write-Host "Repository root:"
          dir
          Write-Host "Contents of the Src folder:"
          dir Src
          Write-Host "Contents of the Src\ECommerceSystem folder:"
          dir "Src\ECommerceSystem"

      # 3. Set up .NET 8.
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      # 4. Install SonarScanner for MSBuild globally.
      - name: Install SonarScanner for MSBuild
        shell: powershell
        run: |
          dotnet tool install --global dotnet-sonarscanner
          # Append the tool location to PATH.
          Add-Content -Path $Env:GITHUB_PATH -Value "$env:USERPROFILE\.dotnet\tools"

      # 5. Restore project dependencies.
      - name: Restore Dependencies
        run: dotnet restore "Src\ECommerceSystem\ECommerceSystem.sln"

      # 6. Begin SonarScanner analysis.
      #    Note: This step specifies the coverage report file (OpenCover format) with Coverlet.
      - name: Run SonarScanner Begin
        run: dotnet sonarscanner begin /k:"binary-brains" /o:"learnathon-by-geeky-solutions" /d:sonar.login="${{ secrets.SONARCLOUD_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="coverage.opencover.xml" /d:sonar.projectBaseDir="Src\ECommerceSystem"

      # 7. Build the project.
      - name: Build Project
        run: dotnet build "Src\ECommerceSystem\ECommerceSystem.sln" --configuration Release

      # 8. Run tests with code coverage enabled.
      #    Coverlet will output an OpenCover formatted report (coverage.opencover.xml) that SonarCloud will import.
      - name: Run Tests with Coverage
        run: dotnet test "Src\ECommerceSystem\ECommerceSystem.sln" --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="coverage.opencover.xml"

      # 9. End SonarScanner analysis.
      - name: Run SonarScanner End
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONARCLOUD_TOKEN }}"
