name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up .NET 8
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      # Step 3: Install SonarScanner for MSBuild
      - name: Install SonarScanner for MSBuild
        run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # Step 4: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore Src/ECommerceSystem/ECommerceSystem.sln

      # **Key: Run SonarScanner Begin BEFORE building the project**
      - name: Run SonarScanner Begin
        run: dotnet sonarscanner begin /k:"binary-brains" /o:"learnathon-by-geeky-solutions" \
            /d:sonar.token="${{ secrets.SONARCLOUD_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.projectBaseDir="Src/ECommerceSystem"

      # Step 5: Build the project
      - name: Build project
        run: dotnet build Src/ECommerceSystem/ECommerceSystem.sln --configuration Release

      # Step 6: (Optional) Run tests and generate a coverage report
      - name: Run tests and generate coverage report
        run: dotnet test Src/ECommerceSystem/ECommerceSystem.sln --configuration Release

      # Step 7: Run SonarScanner End
      - name: Run SonarScanner End
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONARCLOUD_TOKEN }}"
