name: CI/CD with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    name: Build, Test & SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'  # Adjust based on your project version

      - name: Install Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests & Collect Coverage
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"

      - name: Prepare SonarCloud Analysis
        run: |
          dotnet sonarscanner begin /k:"Learnathon-By-Geeky-Solutions_binary-brains" \
          /o:"learnathon-by-geeky-solutions" \
          /d:sonar.token="${{ secrets.SONARCLOUD_TOKEN }}" \
          /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml

      - name: Run SonarCloud Analysis
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONARCLOUD_TOKEN }}"

      - name: Publish Test Coverage Report
        run: |
          report_path=$(find . -name "coverage.cobertura.xml")
          echo "Coverage report path: $report_path"
          bash <(curl -s https://codecov.io/bash) -f "$report_path"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
