name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Restore dependencies
        run: dotnet restore Src/ECommerceSystem/ECommerceSystem.sln

      - name: Build project
        run: dotnet build Src/ECommerceSystem/ECommerceSystem.sln --configuration Release

      - name: Run SonarScanner Begin
        run: dotnet sonarscanner begin /k:"Learnathon-By-Geeky-Solutions_binary-brains" /o:"learnathon-by-geeky-solutions" /d:sonar.token="${{ secrets.SONARCLOUD_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"

      - name: Run tests and generate coverage report
        run: dotnet test Src/ECommerceSystem/ECommerceSystem.sln --configuration Release --logger "trx;LogFileName=test-results.trx"

      - name: Run SonarScanner End
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONARCLOUD_TOKEN }}"
