name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x' # .NET 8

      - name: Restore dependencies
        run: dotnet restore binary-brains/Src/ECommerceSystem/ECommerceSystem.sln # Correct path to solution file

      - name: Build project
        run: dotnet build --no-restore binary-brains/Src/ECommerceSystem/ECommerceSystem.sln

      - name: Run tests and generate coverage report
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" binary-brains/Src/ECommerceSystem/ECommerceSystem.sln

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Start SonarScanner
        run: dotnet sonarscanner begin /k:"Learnathon-By-Geeky-Solutions_binary-brains" /o:"learnathon-by-geeky-solutions" /d:sonar.token="${{ secrets.SONARCLOUD_TOKEN }}" /d:sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml

      - name: End SonarScanner
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONARCLOUD_TOKEN }}"
